<?php
/**
 * scripts/ssh_deploy.php
 *
 * Rsync-over-SSH deploy for wlmonitor: --no-dev composer autoloader, rsync over
 * SSH, then migrations/*.sql run directly via php84 over SSH (tracked in
 * db_migrations). Replaces the legacy ftp_deploy.php.
 *
 * Reads credentials from wlmonitor/config.yaml (generated by mcp/generate.py):
 *
 *   python3 ../mcp/generate.py --app wlmonitor --target world4you
 *   php scripts/ssh_deploy.php
 */

$root = dirname(__DIR__);
require_once $root . '/inc/yaml.php';

$cfg = wl_yaml_load($root . '/config.yaml');

$deploy = $cfg['deploy'] ?? [];
foreach (['ssh_host', 'ssh_user', 'ssh_key', 'ftp_base_dir'] as $k) {
    if (empty($deploy[$k])) {
        fwrite(STDERR, "config.yaml is missing deploy.$k — regenerate with mcp/generate.py --app wlmonitor --target world4you\n");
        exit(1);
    }
}

$sshHost = $deploy['ssh_host'];
$sshUser = $deploy['ssh_user'];
$sshPort = (int) ($deploy['ssh_port'] ?? 22);
$sshKey  = preg_replace('#^~#', getenv('HOME') ?: '', $deploy['ssh_key']);

// World4you layout: /jardyx.com/wlmonitor/ lives at ~/web/jardyx.com/wlmonitor/.
$remoteBase = 'web' . rtrim($deploy['ftp_base_dir'], '/');

$sshOpts = [
    '-i', $sshKey,
    '-p', (string) $sshPort,
    '-o', 'IdentitiesOnly=yes',
    '-o', 'BatchMode=yes',
    '-o', 'StrictHostKeyChecking=accept-new',
];
$sshTarget = $sshUser . '@' . $sshHost;
$sshCmd    = 'ssh ' . implode(' ', array_map('escapeshellarg', $sshOpts));

// ── Regenerate composer autoloader without dev deps ──────────────────────────

$composerBin = null;
foreach ([
    getenv('HOME') . '/bin/composer',
    '/opt/homebrew/bin/composer',
    '/usr/local/bin/composer',
    $root . '/composer.phar',
] as $cand) {
    if (is_executable($cand) || is_readable($cand)) { $composerBin = $cand; break; }
}
if ($composerBin === null) {
    fwrite(STDERR, "composer not found — install it or adjust ssh_deploy.php\n");
    exit(1);
}

function run_proc(array $cmd, ?string $cwd = null): int {
    $descriptors = [0 => ['pipe', 'r'], 1 => STDOUT, 2 => STDERR];
    $proc = proc_open($cmd, $descriptors, $pipes, $cwd);
    if (!is_resource($proc)) return 1;
    fclose($pipes[0]);
    return proc_close($proc);
}

function run_composer(string $bin, string $cwd, array $args): int {
    $cmd = str_ends_with($bin, '.phar') ? array_merge(['php', $bin], $args) : array_merge([$bin], $args);
    return run_proc($cmd, $cwd);
}

echo "Dumping prod autoloader (--no-dev) ...\n";
if (run_composer($composerBin, $root, ['dump-autoload', '--no-dev', '-o']) !== 0) {
    fwrite(STDERR, "composer dump-autoload --no-dev failed\n");
    exit(1);
}

register_shutdown_function(function () use ($root, $composerBin) {
    echo "\nRestoring dev autoloader ...\n";
    run_composer($composerBin, $root, ['dump-autoload', '-o']);
});

// ── Rsync over SSH ───────────────────────────────────────────────────────────
// Excludes mirror the legacy ftp_deploy.php: server-only dirs (data/, backups/,
// config/) and root-only img/ are left untouched by --delete. migrations/ is
// synced — the remote runner reads migrations/*.sql from the deployed tree.

$rsyncExcludes = [
    '.git/',
    '.gitignore',
    '.DS_Store',
    '.claude/',
    '.claude.json',
    '.superpowers/',
    '.phpunit.result.cache',
    '.worktrees/',
    'worktrees/',
    'CLAUDE.md',
    '*.md',
    'phpunit.xml',
    'phpunit.xml.dist',
    'composer.json',
    'composer.lock',
    'composer.phar',
    'config.example.yaml',
    // Nie mit hochladen und — wichtig — durch --delete NICHT entfernen:
    // mail.ini traegt die SMTP-Zugangsdaten, liegt nur auf dem Server und
    // darf nie im Repo stehen (auth TASK-6). Ausgeschlossene Dateien
    // ueberleben --delete.
    'mail.ini',
    'app.dev',
    'app.prod',
    'app.world4you',
    'db.json',
    'db.json.example',
    'tests/',
    'docs/',
    'deprecated/',
    'Archiv/',
    'backlog/',
    'scripts/',
    'firmware/',
    'config/',
    'data/',          // server-only runtime state
    'backups/',       // server-only
    'logs/',
    '/img/',          // root-only static asset dir (matches excludeRootDirs)
    '__pycache__/',
    '*.pyc',
    '*.py',
    'node_modules/',
    'vendor/phpunit/',
    'vendor/sebastian/',
    'vendor/nikic/',
    'vendor/theseer/',
    'vendor/phar-io/',
    'vendor/myclabs/',
    'vendor/staabm/',
    'vendor/bin/',
];

echo "Rsyncing to {$sshTarget}:{$remoteBase} ...\n";
$rsyncCmd = ['rsync', '-avz', '--delete', '--copy-links', '--chmod=Du=rwx,Dgo=rx,Fu=rw,Fgo=r'];
// Protect erikr/auth mail templates from the '*.md' exclude below (first-match-wins).
$rsyncCmd[] = '--include=**/templates/email/*.md';
foreach ($rsyncExcludes as $p) {
    $rsyncCmd[] = '--exclude=' . $p;
}
$rsyncCmd[] = '-e';
$rsyncCmd[] = $sshCmd;
$rsyncCmd[] = rtrim($root, '/') . '/';
$rsyncCmd[] = $sshTarget . ':' . $remoteBase . '/';

if (run_proc($rsyncCmd) !== 0) {
    fwrite(STDERR, "rsync failed\n");
    exit(1);
}

// rsync's --chmod left config.yaml group/other-readable; it holds DB passwords
// and tokens, so lock it back to owner-only on the server.
run_proc(array_merge(['ssh'], $sshOpts,
    [$sshTarget, 'chmod 600 ' . escapeshellarg($remoteBase . '/config.yaml')]));

// ── Run migrations via SSH + php84 ───────────────────────────────────────────

$runner = <<<'PHP'
<?php
$r = getenv('WLMONITOR_ROOT');
require_once $r . '/inc/yaml.php';
$cfg = wl_yaml_load($r . '/config.yaml');
$db  = $cfg['db'];
mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);
$con = mysqli_connect($db['host'], $db['user'], $db['password'], $db['name']);
mysqli_set_charset($con, 'utf8mb4');
$con->query("CREATE TABLE IF NOT EXISTS db_migrations (
    name VARCHAR(255) NOT NULL PRIMARY KEY,
    applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)");
$applied = [];
$res = $con->query('SELECT name FROM db_migrations');
while ($row = $res->fetch_assoc()) $applied[$row['name']] = true;
$files = glob($r . '/migrations/*.sql') ?: []; sort($files); $ran = 0;
foreach ($files as $file) {
    $name = basename($file);
    if (isset($applied[$name])) { echo "skip $name\n"; continue; }
    $sql = file_get_contents($file);
    $con->multi_query($sql);
    do { if ($result = $con->store_result()) $result->free(); }
    while ($con->more_results() && $con->next_result());
    $stmt = $con->prepare('INSERT INTO db_migrations (name) VALUES (?)');
    $stmt->bind_param('s', $name); $stmt->execute(); $stmt->close();
    echo "apply $name\n"; $ran++;
}
echo $ran === 0 ? "Nothing to migrate.\n" : "$ran migration(s) applied.\n";
PHP;

echo "\nRunning migrations on server ...\n";
$tmpRemote = '/tmp/wl_m_' . bin2hex(random_bytes(8)) . '.php';
$remoteScript = sprintf(
    'cat > %s && WLMONITOR_ROOT=%s /usr/bin/php84 %s; rc=$?; rm -f %s; exit $rc',
    escapeshellarg($tmpRemote),
    escapeshellarg($remoteBase),
    escapeshellarg($tmpRemote),
    escapeshellarg($tmpRemote)
);

$sshRun = array_merge(['ssh'], $sshOpts, [$sshTarget, $remoteScript]);
$descriptors = [0 => ['pipe', 'r'], 1 => STDOUT, 2 => STDERR];
$proc = proc_open($sshRun, $descriptors, $pipes);
if (!is_resource($proc)) {
    fwrite(STDERR, "could not start ssh for migration runner\n");
    exit(1);
}
fwrite($pipes[0], $runner);
fclose($pipes[0]);
$rc = proc_close($proc);
if ($rc !== 0) {
    fwrite(STDERR, "migration runner exited with status $rc\n");
    exit($rc);
}

echo "\nDone.\n";
